@echo off
setlocal EnableExtensions

rem Remove files generated by Build-VeilKnit-Rooms.bat.
rem Place this file in the root VeilKnit-Rooms folder.

pushd "%~dp0" || exit /b 1

echo ========================================
echo   VeilKnit Rooms - Clean Build Output
echo ========================================
echo.
echo This removes generated build/output directories while preserving

echo the source code, daemon source, SDK, documentation, and scripts.
echo.

if exist "out" (
    echo Removing out\ ...
    rmdir /S /Q "out"
)

if exist "dist" (
    echo Removing dist\ ...
    rmdir /S /Q "dist"
)

if exist ".vs" (
    echo Removing .vs\ Visual Studio cache...
    rmdir /S /Q ".vs"
)

if exist "CMakeFiles" (
    echo Removing root CMakeFiles\ ...
    rmdir /S /Q "CMakeFiles"
)

if exist "CMakeCache.txt" del /F /Q "CMakeCache.txt"
if exist "cmake_install.cmake" del /F /Q "cmake_install.cmake"
if exist "CTestTestfile.cmake" del /F /Q "CTestTestfile.cmake"
if exist "Testing" rmdir /S /Q "Testing"

echo.
echo Clean complete. The project folder now contains source/project files only.
echo.
popd
exit /b 0
